<?xml version="1.0" encoding="UTF-8"?><testrun name="HsqldbUserDaoTest" project="usermanagement" tests="5" started="5" failures="1" errors="0" ignored="0">
  <testsuite name="ua.nure.cs.petrykin.usermanagement.db.HsqldbUserDaoTest" time="0.898">
    <testcase name="testFindAll" classname="ua.nure.cs.petrykin.usermanagement.db.HsqldbUserDaoTest" time="0.782"/>
    <testcase name="testFind" classname="ua.nure.cs.petrykin.usermanagement.db.HsqldbUserDaoTest" time="0.022"/>
    <testcase name="testCreate" classname="ua.nure.cs.petrykin.usermanagement.db.HsqldbUserDaoTest" time="0.031"/>
    <testcase name="testDelete" classname="ua.nure.cs.petrykin.usermanagement.db.HsqldbUserDaoTest" time="0.044">
      <failure>junit.framework.AssertionFailedError: Expected: &lt;null&gt; but was: ua.nure.cs.petrykin.usermanagement.domain.User@6979e8cb&#13;
	at junit.framework.Assert.fail(Assert.java:57)&#13;
	at junit.framework.Assert.assertTrue(Assert.java:22)&#13;
	at junit.framework.Assert.assertNull(Assert.java:277)&#13;
	at junit.framework.Assert.assertNull(Assert.java:268)&#13;
	at junit.framework.TestCase.assertNull(TestCase.java:438)&#13;
	at ua.nure.cs.petrykin.usermanagement.db.HsqldbUserDaoTest.testDelete(HsqldbUserDaoTest.java:66)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)&#13;
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)&#13;
	at java.lang.reflect.Method.invoke(Unknown Source)&#13;
	at junit.framework.TestCase.runTest(TestCase.java:176)&#13;
	at junit.framework.TestCase.runBare(TestCase.java:141)&#13;
	at junit.framework.TestResult$1.protect(TestResult.java:122)&#13;
	at junit.framework.TestResult.runProtected(TestResult.java:142)&#13;
	at junit.framework.TestResult.run(TestResult.java:125)&#13;
	at junit.framework.TestCase.run(TestCase.java:129)&#13;
	at junit.framework.TestSuite.runTest(TestSuite.java:252)&#13;
	at junit.framework.TestSuite.run(TestSuite.java:247)&#13;
	at org.eclipse.jdt.internal.junit.runner.junit3.JUnit3TestReference.run(JUnit3TestReference.java:121)&#13;
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:678)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)&#13;
&#13;
</failure>
    </testcase>
    <testcase name="testUpdate" classname="ua.nure.cs.petrykin.usermanagement.db.HsqldbUserDaoTest" time="0.018"/>
  </testsuite>
</testrun>
